---
title: "Multiple Logistic Regression"
output: html_document
---

```{r setup, include=FALSE,message=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r ,message=FALSE,warning=FALSE}
require(foreign)
require(MASS)
require(Hmisc)
require(reshape2)
require(sandwich)
require(msm)
```


```{r}

library(nnet)
library(ggplot2)
library(reshape2)

ml <- read.csv("https://raw.githubusercontent.com/RWorkshop/workshopdatasets/master/multilog.csv")
  
```


```{r}
head(ml)
```


```{r}

with(ml, table(ses, prog))
```




```{r}
with(ml, do.call(rbind, 
                 tapply(write, prog, function(x) c(M = mean(x), SD = sd(x)))))

```


```{r}
ml <- ml %>% mutate(prog2 = factor(prog,levels=c("academic","vocation","general")))

test <- nnet::multinom(prog2 ~ ses + write, 
                 data = ml)

summary(test)
```

#### Wald Test Statistics

```{r}
z <- summary(test)$coefficients/summary(test)$standard.errors
z
```

#### P-Values

```{r}
p <- (1 - pnorm(abs(z), 0, 1)) * 2
p
```


```{r}

## extract the coefficients from the model and exponentiate
exp(coef(test))

head(pp <- fitted(test))
```


```{r}
dses <- data.frame(ses = c("low", "middle", "high"), 
                   write = mean(ml$write))
predict(test, newdata = dses, "probs")
```


```{r}
dwrite <- data.frame(ses = rep(c("low", "middle", "high"), each = 41), 
                     write = rep(c(30:70),  3))

```


```{r}
## store the predicted probabilities for each value of ses and write
pp.write <- cbind(dwrite, 
                  predict(test, newdata = dwrite, 
                          type = "probs", se = TRUE))

## calculate the mean probabilities within each level of ses
by(pp.write[, 3:5], pp.write$ses, colMeans)
```


```{r}
## melt data set to long for ggplot2
lpp <- melt(pp.write, id.vars = c("ses", "write"), 
            value.name = "probability")
head(lpp)  # view first few rows
```


```{r}
## plot predicted probabilities across write values for each level of ses
## facetted by program type
ggplot(lpp, aes(x = write, y = probability, colour = ses)) + 
  geom_line() + facet_grid(variable ~
    ., scales = "free")

```